services:
  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: image_processor
      POSTGRES_USER: image_processor
      POSTGRES_PASSWORD: image_processor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U image_processor -d image_processor"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: image_processor
      RABBITMQ_DEFAULT_PASS: image_processor
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  postgres_data:
  rabbitmq_data:
